spring.application.name=backend
# Server Port
# Server Port
server.port=8080

# Cloud PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://ep-purple-wind-b5lah14h-pooler.c-7.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_oHk8C7VbIvDS
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true